"""Final coverage audit using the project's PDF runtime and ignore manifest."""

from __future__ import annotations

import json
from pathlib import Path
import sqlite3

import scripts.audit_full_coverage_v2 as base


IGNORED_GENERATED = {
    ".gitkeep",
    "it/training/2023级计智相关本科人才培养方案.pdf",
}


def _substantive_missing_pages(report: dict) -> list[dict]:
    """Return physical pages with real content that are absent from policy_chunks.

    Empty separator pages and the print-only website footer pages generated by the
    university site are intentionally not treated as knowledge pages.
    """

    connection = sqlite3.connect(report["database"])
    missing: list[dict] = []
    try:
        import pdfplumber

        for source in report["sources"]:
            if source["extension"] != ".pdf" or not source["raw_exists"]:
                continue
            # Split PDFs retain the original book's page numbers in source_page.
            if source["indexed_pages"] == source["pdf_pages"]:
                continue
            indexed = {
                int(row[0])
                for row in connection.execute(
                    "SELECT DISTINCT source_page FROM policy_chunks WHERE source_id=?",
                    (source["source_id"],),
                )
            }
            total = int(source["pdf_pages"] or 0)
            absent = [page for page in range(1, total + 1) if page not in indexed]
            if not absent:
                continue
            local_path = connection.execute(
                "SELECT local_path FROM document_sources WHERE source_id=?",
                (source["source_id"],),
            ).fetchone()[0]
            with pdfplumber.open(local_path) as document:
                for page_number in absent:
                    page = document.pages[page_number - 1]
                    text = (page.extract_text() or "").strip()
                    compact = "".join(text.split())
                    footer_only = (
                        "版权所有@" in compact
                        and "Copyright@" in compact
                        and "Address:" in text
                        and len(compact) < 600
                    )
                    if compact and not footer_only:
                        missing.append(
                            {
                                "source_id": source["source_id"],
                                "source_key": source["source_key"],
                                "doc_title": source["doc_title"],
                                "page": page_number,
                                "text_chars": len(compact),
                                "image_count": len(page.images),
                                "preview": text[:160],
                            }
                        )
    finally:
        connection.close()
    return missing


def pdf_pages(path: Path) -> int | None:
    if path.suffix.lower() != ".pdf":
        return None
    try:
        import pdfplumber

        with pdfplumber.open(path) as document:
            return len(document.pages)
    except Exception:
        return None


def main() -> None:
    base._pdf_pages = pdf_pages
    report = base.audit()
    report["missing_substantive_pages"] = _substantive_missing_pages(report)
    report["substantive_page_coverage_complete"] = not report[
        "missing_substantive_pages"
    ]
    found = set(report["unregistered_raw_files"])
    report["ignored_generated_files"] = sorted(found & IGNORED_GENERATED)
    report["unregistered_raw_files"] = sorted(found - IGNORED_GENERATED)
    output = Path("analysis-output/full-system-v2")
    output.mkdir(parents=True, exist_ok=True)
    (output / "coverage.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (output / "coverage.md").write_text(base.markdown(report), encoding="utf-8")
    print(
        json.dumps(
            {
                key: report[key]
                for key in (
                    "database_counts",
                    "categories",
                    "registered_source_count",
                    "raw_file_count",
                    "missing_raw_files",
                    "unregistered_raw_files",
                    "ignored_generated_files",
                    "zero_chunk_sources",
                    "zero_course_full_books",
                    "substantive_page_coverage_complete",
                    "missing_substantive_pages",
                )
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
